import assert from 'node:assert/strict';
import test from 'node:test';
import { randomUUID } from 'node:crypto';
import Fastify from 'fastify';
import cookie from '@fastify/cookie';
import { isolatedPostgres } from './test-support/postgres-db.ts';

test('PostgreSQL seeded company retirement preserves settings and enforces transactional authorization', { skip: !process.env.TEST_DATABASE_URL && !process.env.CI ? 'TEST_DATABASE_URL absent; real PostgreSQL checks run in CI' : false, timeout: 120_000 }, async t => {
  const { sql } = await isolatedPostgres(t);
  const { registerRoutes } = await import('./routes.ts');
  const { signSession } = await import('./auth.ts');
  const { CEO_POSITION_PROMPT } = await import('./role-playbooks.ts');
  const { dispatchCard } = await import('./dispatch.ts');
  const external=t.mock.method(globalThis,'fetch',async()=>{throw new Error('Retirement must not contact a provider or runtime');});
  t.after(()=>assert.equal(external.mock.callCount(),0));
  const app = Fastify(); t.after(() => app.close()); await app.register(cookie); await registerRoutes(app);
  const [actor] = await sql`INSERT INTO users(email,name,password_hash,role) VALUES('retirement@example.test','Admin','unused','admin') RETURNING *`;
  const [other] = await sql`INSERT INTO users(email,name,password_hash,role) VALUES('other@example.test','Other','unused','admin') RETURNING *`;
  const session = await signSession(actor as any); const otherSession = await signSession(other as any);
  const call = (source: string, target: string, write = false, token = session) => app.inject({ method: write ? 'POST' : 'GET', url: `/api/companies/${source}/retirement${write ? '' : '-preview'}` + (write ? '' : `?targetCompanyId=${target}`), ...(write ? { payload: { targetCompanyId: target } } : {}), headers: { cookie: `session=${token}` } });
  await sql.unsafe('CREATE TABLE retirement_future (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), project_id uuid REFERENCES projects(id))');
  let target:any,third:any,source:any,position:any,project:any,runtime:any,audit:any,targetMemberships:any;
  async function resetFixture() {
  // Only this harness-owned random schema is affected. Every subtest starts from
  // its own rows, so an earlier assertion cannot erase later test preconditions.
  await sql.unsafe('DROP TRIGGER IF EXISTS fail_retirement ON companies');
  await sql.unsafe('TRUNCATE companies CASCADE');
  await sql`DELETE FROM activity_log`;
  await sql`UPDATE users SET status='active'`;
  [target] = await sql`INSERT INTO companies(name,slug) VALUES('Destination','destination') RETURNING *`;
  [third] = await sql`INSERT INTO companies(name,slug) VALUES('Another','another') RETURNING *`;
  for (const company of [target!, third!]) for (const user of [actor!,other!]) await sql`INSERT INTO company_memberships(company_id,user_id,role) VALUES(${company.id},${user.id},'admin')`;
  targetMemberships=await sql`SELECT * FROM company_memberships WHERE company_id=${target!.id} ORDER BY id`;
  [source] = await sql`INSERT INTO companies(name,slug) VALUES('Default Company','default') RETURNING *`;
  await sql`INSERT INTO company_memberships(company_id,user_id,role) VALUES(${source!.id},${actor!.id},'admin')`;
  [position] = await sql`INSERT INTO positions(company_id,name,slug,prompt,description,rank,is_company_boss,can_delegate_across_departments) VALUES(${source!.id},'CEO','ceo',${CEO_POSITION_PROMPT},'Default company boss position generated by migration.',0,true,true) RETURNING *`;
  [project] = await sql`INSERT INTO projects(company_id,name,repo_provider,repo_url,publish_token,auto_merge_after_approval,completion_requires_merge,managed_repo_full_name,merge_readiness,deleted_at) VALUES(${source!.id},'playground','gitea-local','https://git.example.test/original/playground.git','synthetic-project-secret',true,true,'original/playground','{"ready":true,"issues":[],"checkedAt":"2026-01-01"}',now()) RETURNING *`;
  [runtime] = await sql`INSERT INTO agent_runtimes(company_id,name,adapter_type,config) VALUES(${source!.id},'Legacy Runtime','hermes-ssh','{"password":"synthetic-runtime-secret","custom":{"keep":true}}') RETURNING *`;
  [audit] = await sql`INSERT INTO activity_log(company_id,actor_type,actor_id,user_id,action,entity_type,entity_id,details) VALUES(${source!.id},'user',${actor!.id},${actor!.id},'original.action','project',${project!.id},'{"original":"keep","formerCompany":{"keep":"existing"}}') RETURNING *`;
  }
  async function blocker(table:string) { const preview=await call(source.id,target.id); assert.equal(preview.statusCode,200,preview.body);return preview.json().blocking[table]; }

  await t.test('preview requires active admin in both companies, including globally privileged callers', async () => {
    await resetFixture();
    assert.equal((await call(source!.id,target!.id,false,otherSession)).statusCode,403);
    assert.equal((await call(source!.id,target!.id,true,otherSession)).statusCode,403);
    await sql`UPDATE company_memberships SET role='viewer' WHERE company_id=${target!.id} AND user_id=${actor!.id}`;
    assert.equal((await call(source!.id,target!.id)).statusCode,403);
    assert.equal((await call(source!.id,target!.id,true)).statusCode,403);
    await sql`UPDATE company_memberships SET role='admin' WHERE company_id=${target!.id} AND user_id=${actor!.id}`;
    const result = await call(source!.id,target!.id); assert.equal(result.statusCode,200,result.body);
    assert.equal(result.json().canRetire,true); assert.equal(result.json().memberships.length,1);
    assert.equal(result.json().inventory.projects.count,1); assert.equal(result.json().inventory.agent_runtimes.count,1);
    assert.ok(!result.body.includes('synthetic-')); assert.ok(!result.body.includes('https://git'));
    assert.equal((await call(target!.id,third!.id)).statusCode,409);
    assert.equal((await call(source!.id,source!.id)).statusCode,400);
    assert.deepEqual((await sql`SELECT * FROM projects WHERE id=${project!.id}`)[0],project);
    assert.equal((await app.inject({method:'DELETE',url:`/api/companies/${source!.id}`,headers:{cookie:`session=${session}`}})).statusCode,409);
  });
  await t.test('archived linked records, foreign logical references, custom positions, future FKs and conflicts block without writes', async () => {
    await resetFixture();
    const [card]=await sql`INSERT INTO kanban_cards(company_id,project_id,title,body,deleted_at) VALUES(${target!.id},${project!.id},'Linked','Archived',now()) RETURNING id`;
    assert.equal(await blocker('kanban_cards'),1);
    assert.equal((await call(source!.id,target!.id,true)).statusCode,409);
    await sql`DELETE FROM kanban_cards WHERE id=${card!.id}`;
    const [agent]=await sql`INSERT INTO agents(company_id,name,slug,role,runtime_id) VALUES(${target!.id},'Foreign','foreign','Employee',${runtime!.id}) RETURNING id`;
    assert.equal(await blocker('agents'),1);
    await sql`DELETE FROM agents WHERE id=${agent!.id}`;
    await sql`UPDATE positions SET prompt='customized' WHERE id=${position!.id}`;
    assert.equal(await blocker('positions'),1);
    await sql`UPDATE positions SET prompt=${CEO_POSITION_PROMPT} WHERE id=${position!.id}`;
    const [foreignPosition]=await sql`INSERT INTO positions(company_id,name,slug,manager_position_id) VALUES(${target!.id},'Foreign subordinate','foreign-subordinate',${position!.id}) RETURNING id`;
    assert.equal(await blocker('positions'),1);
    await sql`DELETE FROM positions WHERE id=${foreignPosition!.id}`;
    await sql`INSERT INTO retirement_future(project_id) VALUES(${project!.id})`;
    assert.equal(await blocker('retirement_future'),1);
    await sql`DELETE FROM retirement_future`;
    const [conflict]=await sql`INSERT INTO projects(company_id,name,deleted_at) VALUES(${target!.id},'playground',now()) RETURNING id`;
    const denied=await call(source!.id,target!.id,true); assert.equal(denied.statusCode,409,denied.body);
    assert.equal(denied.json().conflicts[0].field,'name'); assert.equal(denied.json().conflicts[0].targetId,conflict!.id);
    assert.deepEqual((await sql`SELECT * FROM projects WHERE id=${project!.id}`)[0],project);
    await sql`DELETE FROM projects WHERE id=${conflict!.id}`;
    const [runtimeConflict]=await sql`INSERT INTO agent_runtimes(company_id,name,adapter_type,is_active) VALUES(${target!.id},'Legacy Runtime','mock',false) RETURNING id`;
    const runtimeDenied=await call(source!.id,target!.id,true); assert.equal(runtimeDenied.statusCode,409,runtimeDenied.body);
    assert.equal(runtimeDenied.json().conflicts[0].table,'agent_runtimes');
    await sql`DELETE FROM agent_runtimes WHERE id=${runtimeConflict!.id}`;
  });
  await t.test('late child insertion and membership revocation committed while retirement waits are rechecked', async () => {
    await resetFixture();
    // Hold a real conflicting table lock and observe the route waiting before committing the child.
    for (const revoke of [false,true]) {
      let release!:()=>void; const gate=new Promise<void>(r=>{release=r;});
      let acquired!:()=>void; const ready=new Promise<void>(r=>{acquired=r;});
      const writer=sql.begin(async tx=>{
        await tx`LOCK TABLE company_memberships IN ROW EXCLUSIVE MODE`;
        if(revoke) await tx`UPDATE company_memberships SET role='viewer' WHERE company_id=${source!.id} AND user_id=${actor!.id}`;
        else await tx`INSERT INTO retirement_future(project_id) VALUES(${project!.id})`;
        acquired(); await gate;
      }).then(()=>({error:null}),error=>{acquired();return {error};});
      await ready;
      const pending=call(source!.id,target!.id,true);
      // inject starts when awaited/then'd; pg_locks makes the interleaving deterministic.
      const responsePromise=Promise.resolve(pending).then(response=>({response,error:null}),error=>({response:null,error}));
      try {
        let waiting=false;
        for(let i=0;i<100;i++) { const rows=await sql`SELECT 1 FROM pg_locks WHERE NOT granted AND relation='company_memberships'::regclass`; if(rows.length){waiting=true;break;} await new Promise(r=>setTimeout(r,10)); }
        assert.equal(waiting,true,'retirement must wait on inventory lock');
      } finally {release(); const written=await writer; assert.equal(written.error,null);}
      const settled=await responsePromise; assert.equal(settled.error,null);const denied=settled.response!; assert.equal(denied.statusCode,revoke?403:409,denied.body);
      await sql`DELETE FROM retirement_future`;
      await sql`UPDATE company_memberships SET role='admin' WHERE company_id=${source!.id} AND user_id=${actor!.id}`;
    }
  });
  await t.test('a write failure rolls back transferred settings and preserved audit', async () => {
    await resetFixture();
    await sql.unsafe("CREATE FUNCTION fail_retirement() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'synthetic retirement failure'; END $$");
    await sql.unsafe('CREATE TRIGGER fail_retirement BEFORE DELETE ON companies FOR EACH ROW EXECUTE FUNCTION fail_retirement()');
    const failed=await call(source!.id,target!.id,true); assert.equal(failed.statusCode,500,failed.body);
    assert.deepEqual((await sql`SELECT * FROM projects WHERE id=${project!.id}`)[0],project);
    assert.deepEqual((await sql`SELECT * FROM agent_runtimes WHERE id=${runtime!.id}`)[0],runtime);
    assert.deepEqual((await sql`SELECT * FROM activity_log WHERE id=${audit!.id}`)[0],audit);
    assert.equal((await sql`SELECT * FROM positions WHERE id=${position!.id}`).length,1);
    await sql.unsafe('DROP TRIGGER fail_retirement ON companies');
  });
  await t.test('retirement preserves settings, policies, IDs and history, invalidating only derived readiness', async () => {
    await resetFixture();
    const result=await call(source!.id,target!.id,true); assert.equal(result.statusCode,200,result.body); const completed=result.json();
    assert.equal(completed.ok,true); assert.deepEqual(completed.movedProjectIds,[project!.id]); assert.deepEqual(completed.movedRuntimeIds,[runtime!.id]);
    const moved=(await sql`SELECT * FROM projects WHERE id=${project!.id}`)[0]!;
    assert.equal(moved.company_id,target!.id); assert.equal(moved.merge_readiness.ready,false); assert.match(moved.merge_readiness.issues.join(' '),/company|transferred/i);
    assert.deepEqual({...moved,company_id:project!.company_id,merge_readiness:project!.merge_readiness},project);
    assert.deepEqual((await sql`SELECT * FROM agent_runtimes WHERE id=${runtime!.id}`)[0],{...runtime,company_id:target!.id});
    const preserved=(await sql`SELECT * FROM activity_log WHERE id=${audit!.id}`)[0]!;
    assert.equal(preserved.company_id,null); assert.deepEqual({...preserved,company_id:audit!.company_id,details:audit!.details},audit);
    assert.equal(preserved.details.original,'keep'); assert.deepEqual(preserved.details.formerCompany,{keep:'existing'});
    assert.equal(preserved.details.companyRetirements[0].source.id,source!.id);
    assert.equal((await sql`SELECT * FROM companies WHERE id=${source!.id}`).length,0);
    assert.equal((await sql`SELECT * FROM company_memberships WHERE company_id=${source!.id}`).length,0);
    assert.equal((await sql`SELECT * FROM positions WHERE id=${position!.id}`).length,0);
    assert.deepEqual(await sql`SELECT * FROM company_memberships WHERE company_id=${target!.id} ORDER BY id`,targetMemberships);
    const record=(await sql`SELECT * FROM activity_log WHERE action='company.retired' AND entity_id=${source!.id}`)[0]!;
    assert.equal(record.company_id,null); assert.ok(!JSON.stringify(record).includes('synthetic-'));
    const [newCard]=await sql`INSERT INTO kanban_cards(company_id,project_id,title,body) VALUES(${target!.id},${project!.id},'After transfer','Readiness remains a gate') RETURNING id`;
    await assert.rejects(dispatchCard(newCard!.id),/managed_merge_unready/);
  });
  await t.test('durable replay is limited to original active actor with current target admin and exact target', async () => {
    await resetFixture();
    const first=await call(source!.id,target!.id,true); assert.equal(first.statusCode,200,first.body);const completed=first.json();
    assert.deepEqual((await call(source!.id,target!.id,true)).json(),completed);
    assert.equal((await call(source!.id,third!.id,true)).statusCode,409);
    assert.equal((await call(source!.id,target!.id,true,otherSession)).statusCode,403);
    await sql`UPDATE company_memberships SET status='inactive' WHERE company_id=${target!.id} AND user_id=${actor!.id}`;
    assert.equal((await call(source!.id,target!.id,true)).statusCode,403);
    await sql`UPDATE company_memberships SET status='active' WHERE company_id=${target!.id} AND user_id=${actor!.id}`;
    await sql`UPDATE users SET status='disabled' WHERE id=${actor!.id}`;
    assert.ok([401,403].includes((await call(source!.id,target!.id,true)).statusCode));
    await sql`UPDATE users SET status='active' WHERE id=${actor!.id}`;
    assert.equal((await sql`SELECT * FROM activity_log WHERE action='company.retired' AND entity_id=${source!.id}`).length,1);
    await sql`UPDATE activity_log SET details='{}' WHERE action='company.retired' AND entity_id=${source!.id}`;
    assert.equal((await call(source!.id,target!.id,true)).statusCode,409);
    assert.equal((await call(randomUUID(),target!.id,true)).statusCode,404);
  });
});
