import assert from 'node:assert/strict';
import test from 'node:test';
import { randomUUID } from 'node:crypto';
import Fastify from 'fastify';
import cookie from '@fastify/cookie';
import { isolatedPostgres } from './test-support/postgres-db.ts';

test('PostgreSQL companyless bootstrap, audit, complete inventory and deletion transactions', { skip: !process.env.TEST_DATABASE_URL && !process.env.CI ? 'TEST_DATABASE_URL absent; real PostgreSQL checks run in CI' : false, timeout: 120_000 }, async t => {
  const { sql } = await isolatedPostgres(t);
  const { migrate } = await import('./db/migrate.ts');
  const { registerRoutes } = await import('./routes.ts');
  const { cleanupUnusedDefault } = await import('./db/companyless-migration.ts');
  const { CEO_POSITION_PROMPT } = await import('./role-playbooks.ts');
  const { companyDeletionInventory } = await import('./company-inventory.ts');
  const app = Fastify(); t.after(() => app.close()); await app.register(cookie); await registerRoutes(app);
  let session = ''; let userId = '';
  const call = (method: 'POST' | 'PUT' | 'GET' | 'DELETE', url: string, payload?: any) => app.inject({ method, url, payload, headers: { cookie: session } });
  await t.test('fresh migrations are companyless and repeated startup does not recreate a seed', async () => {
    assert.equal((await sql`SELECT * FROM companies`).length, 0);
    await migrate(); assert.equal((await sql`SELECT * FROM companies`).length, 0);
    const denied = await call('POST', '/api/auth/bootstrap', { email: 'invalid@example.test', name: 'Denied', password: 'Synthetic-password-2026', token: 'wrong' });
    assert.ok([401,503].includes(denied.statusCode)); assert.equal((await sql`SELECT * FROM users`).length, 0);
    const signup = await call('POST', '/api/auth/signup', { email: 'first@example.test', name: 'First', password: 'Synthetic-password-2026' });
    assert.equal(signup.statusCode, 200, signup.body); assert.equal(signup.json().user.role, 'admin');
    userId = signup.json().user.id; session = String(signup.headers['set-cookie']).split(';')[0]!;
    assert.equal((await sql`SELECT * FROM companies`).length, 0); assert.equal((await sql`SELECT * FROM company_memberships`).length, 0);
  });
  await t.test('global settings/user updates commit and log with no company', async () => {
    assert.equal((await call('PUT','/api/admin/settings',{ signupEnabled: false })).statusCode, 200);
    assert.equal((await call('PUT',`/api/admin/users/${userId}`,{ name: 'Updated' })).statusCode, 200);
    const records = await sql`SELECT * FROM activity_log WHERE company_id IS NULL`;
    assert.ok(records.some(row => row.action === 'admin.settings.updated'));
    assert.ok(records.some(row => row.action === 'admin.user.updated'));
  });
  async function pristine() {
    const [company] = await sql`INSERT INTO companies(name,slug) VALUES('Default Company','default') RETURNING *`;
    await sql`INSERT INTO positions(company_id,name,slug,prompt,description,rank,is_company_boss,can_delegate_across_departments) VALUES(${company!.id},'CEO','ceo',${CEO_POSITION_PROMPT},'Default company boss position generated by migration.',0,true,true)`;
    return company!;
  }
  await t.test('unused exact seed can be cleaned; customization and archived business records are preserved', async () => {
    await pristine(); assert.equal(await sql.begin(tx => cleanupUnusedDefault(tx)), true);
    const customized = await pristine(); await sql`UPDATE companies SET mission='Keep this purpose' WHERE id=${customized.id}`;
    assert.equal(await sql.begin(tx => cleanupUnusedDefault(tx)), false);
    await sql`UPDATE companies SET mission=NULL WHERE id=${customized.id}`;
    const [project] = await sql`INSERT INTO projects(company_id,name,deleted_at) VALUES(${customized.id},'playground',now()) RETURNING id`;
    assert.equal(await sql.begin(tx => cleanupUnusedDefault(tx)), false);
    const inventory = await sql.begin(tx => companyDeletionInventory(tx,customized.id)); assert.equal(inventory.projects?.count,1);
    await sql`DELETE FROM projects WHERE id=${project!.id}`;
    assert.equal(await sql.begin(tx => cleanupUnusedDefault(tx)), true);
  });
  await t.test('actual create-company is visible, archived/new FK rows block deletion, and audit survives empty deletion', async () => {
    const created = await call('POST','/api/companies',{ name: 'Disposable',slug:'disposable' });
    assert.equal(created.statusCode,201,created.body); const company = created.json();
    const [project] = await sql`INSERT INTO projects(company_id,name,deleted_at) VALUES(${company.id},'Archived',now()) RETURNING id`;
    const preview = await call('GET',`/api/companies/${company.id}/deletion-preview`); assert.equal(preview.statusCode,200,preview.body); assert.equal(preview.json().blocking.projects,1);
    assert.equal((await call('DELETE',`/api/companies/${company.id}`)).statusCode,409);
    await sql`DELETE FROM projects WHERE id=${project!.id}`;
    const [one] = await sql`INSERT INTO kanban_cards(company_id,title,body) VALUES(${company.id},'One','Test composite links') RETURNING id`;
    const [two] = await sql`INSERT INTO kanban_cards(company_id,title,body) VALUES(${company.id},'Two','Test composite links') RETURNING id`;
    await sql`INSERT INTO card_dependencies(card_id,depends_on_card_id) VALUES(${one!.id},${two!.id})`;
    const composite = await call('GET',`/api/companies/${company.id}/deletion-preview`);
    assert.equal(composite.statusCode,200,composite.body);assert.equal(composite.json().blocking.card_dependencies,1);
    assert.equal((await call('DELETE',`/api/companies/${company.id}`)).statusCode,409);
    await sql`DELETE FROM card_dependencies WHERE card_id=${one!.id}`;
    await sql`DELETE FROM kanban_cards WHERE company_id=${company.id}`;
    // An additional actual FK is discovered without changing application table lists.
    await sql.unsafe('CREATE TABLE task4_future_rows (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID REFERENCES companies(id))');
    await sql`INSERT INTO task4_future_rows(company_id) VALUES(${company.id})`;
    assert.equal((await call('GET',`/api/companies/${company.id}/deletion-preview`)).json().blocking.task4_future_rows,1);
    await sql`DELETE FROM task4_future_rows WHERE company_id=${company.id}`;
    const empty = await call('GET',`/api/companies/${company.id}/deletion-preview`); assert.equal(empty.json().canDelete,true);
    // A reference written after the preview must be seen by the write-time recheck.
    await sql`INSERT INTO task4_future_rows(company_id) VALUES(${company.id})`;
    assert.equal((await call('DELETE',`/api/companies/${company.id}`)).statusCode,409);
    await sql`DELETE FROM task4_future_rows WHERE company_id=${company.id}`;
    const removed = await call('DELETE',`/api/companies/${company.id}`); assert.equal(removed.statusCode,200,removed.body);
    const audit = await sql`SELECT * FROM activity_log WHERE entity_id=${company.id}`;
    assert.ok(audit.some(row => row.action==='company.created')); assert.ok(audit.every(row => row.company_id===null && row.details.formerCompany.id===company.id));
  });
});
