import type { FastifyInstance, FastifyReply, FastifyRequest } from 'fastify';
import { z } from 'zod';
import { requireAuth } from './auth.ts';
import { sql } from './db/client.ts';
import { companyDeletionInventory, companyInventoryCatalog, lockCompanyInventory, type InventorySql } from './company-inventory.ts';
import { CEO_POSITION_PROMPT } from './role-playbooks.ts';

const companyIdentity = z.object({ id: z.string().uuid(), name: z.string(), slug: z.string() }).strict();
const retirementResult = z.object({
  ok: z.literal(true), source: companyIdentity, target: companyIdentity,
  movedProjectIds: z.array(z.string().uuid()), movedRuntimeIds: z.array(z.string().uuid()),
  removedPositionIds: z.array(z.string().uuid()), removedMembershipIds: z.array(z.string().uuid()),
  preservedActivityIds: z.array(z.string().uuid()),
  readinessIssue: z.string(),
}).strict();
const readinessIssue = 'Company context changed: transferred repository URLs and permissions are unchanged. Recheck target agent repository access and managed merge readiness before execution.';
const allowed = new Set(['projects','agent_runtimes','positions','company_memberships','activity_log']);

function unusedSeedPosition(row: Record<string, unknown>, sourceId: string) {
  const expected: Record<string, unknown> = { company_id: sourceId, name: 'CEO', slug: 'ceo', prompt: CEO_POSITION_PROMPT, description: 'Default company boss position generated by migration.', rank: 0, is_company_boss: true, can_delegate_across_departments: true, default_department_id: null, manager_position_id: null, review_domain: null, is_active: true };
  return Object.entries(row).every(([key,value]) => ['id','created_at','updated_at'].includes(key) || (key in expected && value === expected[key]));
}

/** Same complete FK/logical closure as ordinary deletion, with only these five exceptions. */
async function previewRetirement(tx: InventorySql, source: z.infer<typeof companyIdentity>, target: z.infer<typeof companyIdentity>, catalog: Awaited<ReturnType<typeof companyInventoryCatalog>>) {
  const inventory=await companyDeletionInventory(tx,source.id,catalog);
  const roles=await tx.unsafe('SELECT * FROM positions WHERE company_id=$1 ORDER BY id',[source.id]);
  const blocking: Record<string,number>={};
  for(const [table,rows] of Object.entries(inventory)) {
    const count=allowed.has(table)?rows.foreignCount:rows.count;
    if(count)blocking[table]=count;
  }
  const custom=roles.filter(row=>!unusedSeedPosition(row,source.id)).length;
  if(custom)blocking.positions=(blocking.positions??0)+custom;
  const projects=await tx.unsafe('SELECT id,name,deleted_at AS "deletedAt" FROM projects WHERE company_id=$1 ORDER BY id',[source.id]);
  const runtimes=await tx.unsafe('SELECT id,name,adapter_type AS "adapterType",is_active AS "isActive" FROM agent_runtimes WHERE company_id=$1 ORDER BY id',[source.id]);
  const memberships=await tx.unsafe('SELECT id,user_id AS "userId",role,status FROM company_memberships WHERE company_id=$1 ORDER BY id',[source.id]);
  const conflicts: Array<{table:string;field:string;value:string;sourceId:string;targetId:string}>=[];
  for(const table of ['projects','agent_runtimes']) {
    // These are fixed application identifiers. Include archived rows and future slug fields.
    const rows=await tx.unsafe(`SELECT s.id AS source_id,t.id AS target_id,s.name,to_jsonb(s)->>'slug' AS slug, s.name=t.name AS name_conflict FROM ${table} s JOIN ${table} t ON t.company_id=$2 AND (s.name=t.name OR (to_jsonb(s)->>'slug' IS NOT NULL AND to_jsonb(s)->>'slug'=to_jsonb(t)->>'slug')) WHERE s.company_id=$1 ORDER BY s.id,t.id`,[source.id,target.id]);
    for(const row of rows) conflicts.push({table,field:row.name_conflict?'name':'slug',value:row.name_conflict?row.name:row.slug,sourceId:row.source_id,targetId:row.target_id});
  }
  return {source,target,canRetire:!Object.keys(blocking).length&&!conflicts.length,blocking,conflicts,inventory,projects,runtimes,positions:roles.map(row=>({id:row.id,name:row.name,slug:row.slug,unusedSeed:unusedSeedPosition(row,source.id)})),memberships,readinessIssue};
}

async function retirement(tx: InventorySql, sourceId: string, targetId: string, actorId: string, write: boolean) {
  // Match generic deletion's table-before-row order. Tables fence FK AND logical
  // child/membership writes; company row locks alone cannot fence non-FK IDs.
  const catalog=write?await lockCompanyInventory(tx):await companyInventoryCatalog(tx);
  const companies=await tx.unsafe(`SELECT id,name,slug,setup_key,setup_draft FROM companies WHERE id IN ($1,$2) ORDER BY id${write?' FOR UPDATE':''}`,[sourceId,targetId]);
  const target=companies.find(row=>row.id===targetId);
  const [actor]=await tx.unsafe(`SELECT id FROM users WHERE id=$1 AND status='active'${write?' FOR SHARE':''}`,[actorId]);
  const membership=await tx.unsafe("SELECT company_id FROM company_memberships WHERE user_id=$1 AND company_id IN ($2,$3) AND role='admin' AND status='active'",[actorId,sourceId,targetId]);
  if(!actor||!membership.some(row=>row.company_id===targetId))return {error:'company_role_required'};
  if(!target)return {error:'company_not_found'};
  const source=companies.find(row=>row.id===sourceId);
  if(!source) {
    if(!write)return {error:'company_not_found'};
    const records=await tx.unsafe("SELECT actor_type,actor_id,user_id,details FROM activity_log WHERE action='company.retired' AND entity_type='company' AND entity_id=$1 AND company_id IS NULL",[sourceId]);
    if(!records.length)return {error:'company_not_found'};
    if(records.length!==1)return {error:'company_retirement_audit_invalid'};
    const record=records[0];
    if(record.actor_type!=='user'||record.actor_id!==actorId||record.user_id!==actorId)return {error:'company_role_required'};
    const prior=retirementResult.safeParse(record.details?.result);
    if(!prior.success||prior.data.source.id!==sourceId||record.details?.version!==1)return {error:'company_retirement_audit_invalid'};
    if(prior.data.target.id!==targetId)return {error:'company_retirement_target_mismatch'};
    return prior.data;
  }
  if(!membership.some(row=>row.company_id===sourceId))return {error:'company_role_required'};
  if(source.name!=='Default Company'||source.slug!=='default'||source.setup_key!==null||source.setup_draft!==null)return {error:'company_retirement_source_not_legacy_default'};
  const identity=(row:any)=>companyIdentity.parse({id:row.id,name:row.name,slug:row.slug});
  const preview=await previewRetirement(tx,identity(source),identity(target),catalog);
  if(!write)return preview;
  if(!preview.canRetire)return {error:'company_retirement_blocked',...preview};
  const result: z.infer<typeof retirementResult>={ok:true,source:preview.source,target:preview.target,
    movedProjectIds:preview.projects.map(row=>row.id),movedRuntimeIds:preview.runtimes.map(row=>row.id),
    removedPositionIds:preview.positions.map(row=>row.id),removedMembershipIds:preview.memberships.map(row=>row.id),
    preservedActivityIds:preview.inventory.activity_log?.ids??[],readinessIssue};
  // Only context and the derived readiness cache change; all configured policy,
  // credentials, legacy adapter configuration, timestamps and repository URLs stay.
  await tx.unsafe("UPDATE projects SET company_id=$2,merge_readiness=jsonb_build_object('ready',false,'issues',jsonb_build_array($3::text),'checkedAt',$4::text) WHERE company_id=$1",[sourceId,targetId,readinessIssue,new Date().toISOString()]);
  await tx.unsafe('UPDATE agent_runtimes SET company_id=$2 WHERE company_id=$1',[sourceId,targetId]);
  // Preserve existing provenance keys/details, even for legacy non-object JSON.
  await tx.unsafe(`UPDATE activity_log SET company_id=NULL,details=
    (CASE WHEN jsonb_typeof(details)='object' THEN details ELSE jsonb_build_object('originalDetails',details) END) ||
    jsonb_build_object('companyRetirements',
      (CASE WHEN details ? 'companyRetirements' THEN CASE WHEN jsonb_typeof(details->'companyRetirements')='array' THEN details->'companyRetirements' ELSE jsonb_build_array(details->'companyRetirements') END ELSE '[]'::jsonb END) || jsonb_build_array($2::jsonb))
    WHERE id::text IN (SELECT jsonb_array_elements_text($1::jsonb))`,[JSON.stringify(result.preservedActivityIds),JSON.stringify({source:result.source,target:result.target})]);
  await tx.unsafe('DELETE FROM positions WHERE company_id=$1',[sourceId]);
  await tx.unsafe('DELETE FROM company_memberships WHERE company_id=$1',[sourceId]);
  await tx.unsafe('DELETE FROM companies WHERE id=$1',[sourceId]);
  // actor_id is TEXT while user_id is UUID: bind them separately, as in deletion.
  await tx.unsafe("INSERT INTO activity_log(company_id,actor_type,actor_id,user_id,action,entity_type,entity_id,details) VALUES(NULL,'user',$1,$2::uuid,'company.retired','company',$3,$4::jsonb)",[actorId,actorId,sourceId,JSON.stringify({version:1,result})]);
  return result;
}

export function registerCompanyRetirementRoutes(app: FastifyInstance) {
  const handler=(write:boolean)=>async(request:FastifyRequest,reply:FastifyReply)=>{
    const actor=await requireAuth(request,reply);if(!actor)return reply;
    const sourceId=z.string().uuid().parse((request.params as {id:string}).id);
    const {targetCompanyId}=z.object({targetCompanyId:z.string().uuid()}).strict().parse(write?request.body:request.query);
    if(sourceId===targetCompanyId)return reply.code(400).send({error:'company_retirement_same_target'});
    try {
      const result=write?await sql.begin(tx=>retirement(tx,sourceId,targetCompanyId,actor.id,true)):await sql.begin('isolation level repeatable read read only',async tx=>{
        await tx.unsafe("SET LOCAL statement_timeout='5000ms'");return retirement(tx,sourceId,targetCompanyId,actor.id,false);
      });
      if('error' in result)return reply.code(result.error==='company_role_required'?403:result.error==='company_not_found'?404:409).send(result);
      return result;
    } catch(error) {
      if(['55P03','57014','40P01','23503','23505'].includes(String((error as {code?:string}).code)))return reply.code(409).send({error:'company_retirement_busy',message:'Company records changed or are busy. Refresh the retirement preview and retry.'});
      throw error;
    }
  };
  app.get('/api/companies/:id/retirement-preview',handler(false));
  app.post('/api/companies/:id/retirement',handler(true));
}
