import assert from 'node:assert/strict';
import test from 'node:test';
import { randomUUID } from 'node:crypto';
import Fastify from 'fastify';
import cookie from '@fastify/cookie';
import { agents, companies, departments, knowledgeDocs, users, companyMemberships, chatSessions, chatMessages, promptLogs } from './db/schema.ts';
import { memoryDb } from './test-support/memory-db.ts';
import { registerChatRoutes } from './chat.ts';
import { signSession } from './auth.ts';
import { getAdapter } from './adapters/registry.ts';
test('actual Direct Chat bootstrap and continuation refresh edited role/docs and redact returned metadata', async t => {
  const company: any = { id: randomUUID(), name: 'Acme', slug: 'acme' };
  const user: any = { id: randomUUID(), email: 'operator@example.test', role: 'operator' };
  const head: any = { id: randomUUID(), companyId: company.id, name: 'Head', slug: 'head', departmentId: randomUUID(), isActive: true, isBusy: false, adapterType: 'codex-app', adapterConfig: {}, giteaToken: 'synthetic-chat-credential' };
  const department: any = { id: head.departmentId, companyId: company.id, name: 'Engineering', slug: 'engineering', headAgentId: head.id, headRolePrompt: 'Initial role responsibility' };
  const session: any = { id: randomUUID(), companyId: company.id, agentId: head.id, projectId: null, title: 'Chat with Head', userId: user.id };
  const doc: any = { id: randomUUID(), companyId: company.id, title: 'Engineering charter', tags: ['ENGINEERING'], body: 'Initial department instructions', updatedAt: new Date() };
  const state = memoryDb(t, [[companies, [company]], [users, [user]], [companyMemberships, [{ userId: user.id, companyId: company.id, role: 'operator', status: 'active' }]], [agents, [head]], [departments, [department]], [chatSessions, [session]], [knowledgeDocs, [doc]]]);
  const prompts: string[] = [];
  t.mock.method(getAdapter('codex-app'), 'dispatch', async (_agent: any, task: any) => { prompts.push(task.body); return { success: true, output: `Answer ${head.giteaToken}`, sessionId: 'chat-runtime-session', tokensUsed: 0, costUsd: 0, durationSeconds: 1 }; });
  const app = Fastify(); t.after(() => app.close()); await app.register(cookie); await registerChatRoutes(app);
  const headers = { cookie: `session=${await signSession(user)}` };
  const first = await app.inject({ method: 'POST', url: `/api/chat/sessions/${session.id}/messages`, headers, payload: { body: 'Explain the charter' } });
  assert.equal(first.statusCode, 200, first.body); assert.match(prompts[0]!, /Initial role responsibility/); assert.match(prompts[0]!, /Initial department instructions/);
  department.headRolePrompt = 'Edited role responsibility'; doc.body = 'Edited department instructions'; doc.updatedAt = new Date(Date.now() + 1000);
  const second = await app.inject({ method: 'POST', url: `/api/chat/sessions/${session.id}/messages`, headers, payload: { body: 'Continue using the current charter' } });
  assert.equal(second.statusCode, 200, second.body); assert.match(prompts[1]!, /Edited role responsibility/); assert.match(prompts[1]!, /Edited department instructions/);
  assert.ok(!JSON.stringify([...state.rows(chatMessages), ...state.rows(promptLogs)]).includes(head.giteaToken));
});
