import assert from 'node:assert/strict';
import test from 'node:test';
import { randomUUID } from 'node:crypto';
import Fastify from 'fastify';
import cookie from '@fastify/cookie';
import { isolatedPostgres } from './test-support/postgres-db.ts';

test('PostgreSQL companyless bootstrap, audit, complete inventory and deletion transactions', { skip: !process.env.TEST_DATABASE_URL && !process.env.CI ? 'TEST_DATABASE_URL absent; real PostgreSQL checks run in CI' : false, timeout: 120_000 }, async t => {
  const { sql } = await isolatedPostgres(t);
  const { migrate } = await import('./db/migrate.ts');
  const { registerRoutes } = await import('./routes.ts');
  const { cleanupUnusedDefault } = await import('./db/companyless-migration.ts');
  const { CEO_POSITION_PROMPT } = await import('./role-playbooks.ts');
  const { companyDeletionInventory } = await import('./company-inventory.ts');
  const app = Fastify(); t.after(() => app.close()); await app.register(cookie); await registerRoutes(app);
  let session = ''; let userId = '';
  const call = (method: 'POST' | 'PUT' | 'GET' | 'DELETE', url: string, payload?: any) => app.inject({ method, url, payload, headers: { cookie: session } });
  await t.test('fresh migrations are companyless and repeated startup does not recreate a seed', async () => {
    assert.equal((await sql`SELECT * FROM companies`).length, 0);
    await migrate(); assert.equal((await sql`SELECT * FROM companies`).length, 0);
    const denied = await call('POST', '/api/auth/bootstrap', { email: 'invalid@example.test', name: 'Denied', password: 'Synthetic-password-2026', token: 'wrong' });
    assert.ok([401,503].includes(denied.statusCode)); assert.equal((await sql`SELECT * FROM users`).length, 0);
    const previousToken=process.env.BOOTSTRAP_TOKEN;process.env.BOOTSTRAP_TOKEN='Synthetic-bootstrap-token-2026';
    try {
      const bootstrap=await call('POST','/api/auth/bootstrap',{email:'bootstrap@example.test',name:'Bootstrap',password:'Synthetic-password-2026',token:process.env.BOOTSTRAP_TOKEN});
      assert.equal(bootstrap.statusCode,200,bootstrap.body);assert.equal(bootstrap.json().user.role,'admin');
      assert.equal((await sql`SELECT * FROM companies`).length,0);
      const bootId=bootstrap.json().user.id;
      await sql`DELETE FROM activity_log WHERE user_id=${bootId}`;await sql`DELETE FROM users WHERE id=${bootId}`;
    } finally {if(previousToken===undefined)delete process.env.BOOTSTRAP_TOKEN;else process.env.BOOTSTRAP_TOKEN=previousToken;}
    const signup = await call('POST', '/api/auth/signup', { email: 'first@example.test', name: 'First', password: 'Synthetic-password-2026' });
    assert.equal(signup.statusCode, 200, signup.body); assert.equal(signup.json().user.role, 'admin');
    userId = signup.json().user.id; session = String(signup.headers['set-cookie']).split(';')[0]!;
    assert.equal((await sql`SELECT * FROM companies`).length, 0); assert.equal((await sql`SELECT * FROM company_memberships`).length, 0);
  });
  await t.test('global settings/user updates commit and log with no company', async () => {
    assert.equal((await call('PUT','/api/admin/settings',{ signupEnabled: false })).statusCode, 200);
    assert.equal((await call('PUT',`/api/admin/users/${userId}`,{ name: 'Updated' })).statusCode, 200);
    const records = await sql`SELECT * FROM activity_log WHERE company_id IS NULL`;
    assert.ok(records.some(row => row.action === 'admin.settings.updated'));
    assert.ok(records.some(row => row.action === 'admin.user.updated'));
  });
  async function pristine() {
    const [company] = await sql`INSERT INTO companies(name,slug) VALUES('Default Company','default') RETURNING *`;
    await sql`INSERT INTO positions(company_id,name,slug,prompt,description,rank,is_company_boss,can_delegate_across_departments) VALUES(${company!.id},'CEO','ceo',${CEO_POSITION_PROMPT},'Default company boss position generated by migration.',0,true,true)`;
    return company!;
  }
  await t.test('unused exact seed can be cleaned; customization and archived business records are preserved', async () => {
    await pristine(); assert.equal(await sql.begin(tx => cleanupUnusedDefault(tx)), true);
    const setupSeed = await pristine();
    await sql`UPDATE companies SET setup_key=${randomUUID()} WHERE id=${setupSeed.id}`;
    assert.equal(await sql.begin(tx => cleanupUnusedDefault(tx)),false);
    await sql`UPDATE companies SET setup_key=NULL,setup_draft='{"stage":"boss"}'::jsonb WHERE id=${setupSeed.id}`;
    assert.equal(await sql.begin(tx => cleanupUnusedDefault(tx)),false);
    await sql`UPDATE companies SET setup_draft=NULL WHERE id=${setupSeed.id}`;
    assert.equal(await sql.begin(tx => cleanupUnusedDefault(tx)),true);
    const customized = await pristine(); await sql`UPDATE companies SET mission='Keep this purpose' WHERE id=${customized.id}`;
    assert.equal(await sql.begin(tx => cleanupUnusedDefault(tx)), false);
    await sql`UPDATE companies SET mission=NULL WHERE id=${customized.id}`;
    const [project] = await sql`INSERT INTO projects(company_id,name,deleted_at) VALUES(${customized.id},'playground',now()) RETURNING id`;
    assert.equal(await sql.begin(tx => cleanupUnusedDefault(tx)), false);
    const inventory = await sql.begin(tx => companyDeletionInventory(tx,customized.id)); assert.equal(inventory.projects?.count,1);
    await sql`DELETE FROM projects WHERE id=${project!.id}`;
    assert.equal(await sql.begin(tx => cleanupUnusedDefault(tx)), true);
  });
  await t.test('actual create-company is visible, archived/new FK rows block deletion, and audit survives empty deletion', async () => {
    const created = await call('POST','/api/companies',{ name: 'Disposable',slug:'disposable' });
    assert.equal(created.statusCode,201,created.body); const company = created.json();
    const [project] = await sql`INSERT INTO projects(company_id,name,deleted_at) VALUES(${company.id},'Archived',now()) RETURNING id`;
    const preview = await call('GET',`/api/companies/${company.id}/deletion-preview`); assert.equal(preview.statusCode,200,preview.body); assert.equal(preview.json().blocking.projects,1);
    assert.equal((await call('DELETE',`/api/companies/${company.id}`)).statusCode,409);
    await sql`DELETE FROM projects WHERE id=${project!.id}`;
    const [one] = await sql`INSERT INTO kanban_cards(company_id,title,body) VALUES(${company.id},'One','Test composite links') RETURNING id`;
    const [two] = await sql`INSERT INTO kanban_cards(company_id,title,body) VALUES(${company.id},'Two','Test composite links') RETURNING id`;
    await sql`INSERT INTO card_dependencies(card_id,depends_on_card_id) VALUES(${one!.id},${two!.id})`;
    const composite = await call('GET',`/api/companies/${company.id}/deletion-preview`);
    assert.equal(composite.statusCode,200,composite.body);assert.equal(composite.json().blocking.card_dependencies,1);
    assert.equal((await call('DELETE',`/api/companies/${company.id}`)).statusCode,409);
    await sql`DELETE FROM card_dependencies WHERE card_id=${one!.id}`;
    await sql`DELETE FROM kanban_cards WHERE company_id=${company.id}`;
    // An additional actual FK is discovered without changing application table lists.
    await sql.unsafe('CREATE TABLE task4_future_rows (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID REFERENCES companies(id))');
    await sql`INSERT INTO task4_future_rows(company_id) VALUES(${company.id})`;
    assert.equal((await call('GET',`/api/companies/${company.id}/deletion-preview`)).json().blocking.task4_future_rows,1);
    await sql`DELETE FROM task4_future_rows WHERE company_id=${company.id}`;
    const empty = await call('GET',`/api/companies/${company.id}/deletion-preview`); assert.equal(empty.json().canDelete,true);
    // A reference written after the preview must be seen by the write-time recheck.
    await sql`INSERT INTO task4_future_rows(company_id) VALUES(${company.id})`;
    assert.equal((await call('DELETE',`/api/companies/${company.id}`)).statusCode,409);
    await sql`DELETE FROM task4_future_rows WHERE company_id=${company.id}`;
    const removed = await call('DELETE',`/api/companies/${company.id}`); assert.equal(removed.statusCode,200,removed.body);
    const audit = await sql`SELECT * FROM activity_log WHERE entity_id=${company.id}`;
    assert.ok(audit.some(row => row.action==='company.created')); assert.ok(audit.every(row => row.company_id===null && row.details.formerCompany.id===company.id));
  });
  await t.test('actual setup routes resume persisted entities and require a successful endpoint response before enabling dispatch',async t=>{
    const setupKey=randomUUID();const input={setupKey,name:'PG Studio',slug:'pg-studio'};
    const first=await call('POST','/api/company-setup',input);assert.equal(first.statusCode,201,first.body);
    const conflict=await call('POST','/api/company-setup',{...input,setupKey:randomUUID()});assert.equal(conflict.statusCode,409,conflict.body);assert.equal(conflict.json().error,'setup_slug_taken');
    const id=first.json().company.id;assert.equal((await call('POST','/api/company-setup',input)).json().company.id,id);
    for(const payload of [{step:'boss',name:'Boss',slug:'boss'},{step:'boss',name:'Boss',slug:'boss'},{step:'department',name:'Team',slug:'team'},{step:'head',name:'Head',slug:'head'},{step:'runtime',name:'A2A',a2aBaseUrl:'https://runtime.example.test'}]){
      const saved=await call('PUT',`/api/companies/${id}/setup`,payload);assert.equal(saved.statusCode,200,saved.body);
    }
    assert.equal((await sql`SELECT * FROM agents WHERE company_id=${id}`).length,2);
    assert.equal((await call('PUT',`/api/companies/${id}/setup`,{step:'finish'})).statusCode,409);
    t.mock.method(globalThis,'fetch',async()=>new Response(JSON.stringify({name:'Synthetic live endpoint'}),{status:200}));
    const checked=await call('POST',`/api/companies/${id}/setup/probe`);assert.equal(checked.statusCode,200,checked.body);assert.ok(checked.json().results.every((row:any)=>row.success));
    const ready=await call('PUT',`/api/companies/${id}/setup`,{step:'finish'});assert.equal(ready.statusCode,200,ready.body);
    assert.equal((await sql`SELECT auto_dispatch_enabled FROM companies WHERE id=${id}`)[0]!.auto_dispatch_enabled,true);
    for (const mode of ['a2a','codex-app-server']) {
      const [shared] = await sql`INSERT INTO agent_runtimes(company_id,name,adapter_type,config) VALUES(${id},${`Shared ${mode}`},${mode},'{"a2aBaseUrl":"https://shared.example.test","a2aBearerToken":"synthetic-sentinel","custom":"preserve"}'::jsonb) RETURNING *`;
      const [other] = await sql`INSERT INTO agents(company_id,name,slug,role,adapter_type,runtime_id) VALUES(${id},'Other',${`other-${mode}`},'Employee',${mode},${shared!.id}) RETURNING *`;
      const selected=await call('PUT',`/api/companies/${id}/setup`,{step:'runtime',runtimeId:shared!.id});
      assert.equal(selected.statusCode,200,selected.body);
      const creation={step:'runtime',runtimeCreateKey:randomUUID(),name:'Distinct A2A',a2aBaseUrl:'https://distinct.example.test'};
      // Actual concurrent route requests serialize on the company row and reuse the operation.
      const attempts=await Promise.all([call('PUT',`/api/companies/${id}/setup`,creation),call('PUT',`/api/companies/${id}/setup`,creation)]);
      for(const attempt of attempts)assert.equal(attempt.statusCode,200,attempt.body);
      const newId=attempts[0]!.json().draft.runtimeId;
      assert.notEqual(newId,shared!.id);assert.equal(attempts[1]!.json().draft.runtimeId,newId);
      assert.equal((await sql`SELECT * FROM agent_runtimes WHERE id=${newId}`)[0]!.adapter_type,'a2a');
      assert.equal((await sql`SELECT * FROM agent_runtimes WHERE company_id=${id} AND name='Distinct A2A'`).length,mode==='a2a'?1:2);
      assert.deepEqual((await sql`SELECT * FROM agent_runtimes WHERE id=${shared!.id}`)[0],shared);
      assert.deepEqual((await sql`SELECT * FROM agents WHERE id=${other!.id}`)[0],other);
    }
    await call('POST',`/api/companies/${id}/setup/probe`);
    assert.equal((await call('PUT',`/api/companies/${id}/setup`,{step:'finish'})).statusCode,200);
    const before=(await call('GET',`/api/companies/${id}/setup`)).json();
    await sql`UPDATE departments SET head_agent_id=NULL WHERE id=${before.department.id}`;
    const broken=(await call('GET',`/api/companies/${id}/setup`)).json();
    assert.equal(broken.status,'needs_attention');assert.equal(broken.company.autoDispatchEnabled,true);
    const reopened=await call('PUT',`/api/companies/${id}/setup`,{step:'reopen'});
    assert.equal(reopened.statusCode,200,reopened.body);assert.equal(reopened.json().company.autoDispatchEnabled,false);
    const fixed=await call('PUT',`/api/companies/${id}/setup`,{step:'head',name:'Head',slug:'head'});
    assert.equal(fixed.statusCode,200,fixed.body);assert.equal(fixed.json().head.id,before.head.id);
    assert.equal((await call('PUT',`/api/companies/${id}/setup`,{step:'finish'})).statusCode,409);
    await call('POST',`/api/companies/${id}/setup/probe`);
    assert.equal((await call('PUT',`/api/companies/${id}/setup`,{step:'finish'})).statusCode,200);
    assert.equal((await sql`SELECT * FROM agents WHERE company_id=${id}`).length,4);
    assert.equal((await sql`SELECT * FROM departments WHERE company_id=${id}`).length,1);
  });

});
