import assert from 'node:assert/strict';
import test from 'node:test';
import { randomUUID } from 'node:crypto';
import Fastify from 'fastify';
import cookie from '@fastify/cookie';
import { agents, companies, companyMemberships, kanbanCards, users } from './db/schema.ts';
import { memoryDb } from './test-support/memory-db.ts';
import { registerRoutes } from './routes.ts';
import { signSession } from './auth.ts';
import { extractChatWorkItems } from './chat-work-items.ts';
import { normalizeAgentResult } from './agent-results.ts';
import { createCardSchema } from '@megacorps/shared';
test('coordination-only is an explicit operator choice, preserved on partial edits, never granted by agent output', async t => {
  const company: any = { id: randomUUID(), name: 'Company' };
  const user: any = { id: randomUUID(), email: 'operator@example.test', role: 'operator' };
  const state = memoryDb(t, [[companies, [company]], [users, [user]], [companyMemberships, [{ userId: user.id, companyId: company.id, role: 'operator', status: 'active' }]], [agents, []]]);
  const app = Fastify(); t.after(() => app.close()); await app.register(cookie); await registerRoutes(app);
  const headers = { cookie: `session=${await signSession(user)}` };
  const created = await app.inject({ method: 'POST', url: '/api/cards', headers, payload: { companyId: company.id, title: 'Coordinate strategy', body: 'Acceptance: record the strategy', coordinationOnly: true, requiresApproval: true } });
  assert.equal(created.statusCode, 201, created.body);
  const card = created.json(); assert.equal(card.coordinationOnly, true); assert.equal(card.requiresApproval, true);
  const edited = await app.inject({ method: 'PUT', url: `/api/cards/${card.id}`, headers, payload: { title: 'Updated strategy' } });
  assert.equal(edited.statusCode, 200, edited.body); assert.equal(state.rows(kanbanCards)[0]!.coordinationOnly, true);
  assert.equal(createCardSchema.parse({ title: 'Ordinary work', body: 'Do work', requiresApproval: true }).coordinationOnly, false);
  const report = normalizeAgentResult({ report: { kind: 'megacorps-report', status: 'completed', summary: 'Result', coordinationOnly: true } });
  assert.ok(!('coordinationOnly' in report.report!));
  const chat = extractChatWorkItems(JSON.stringify({ kind: 'megacorps-chat-actions', actions: [{ action: 'create_card', title: 'Build', body: 'Acceptance: works', coordinationOnly: true }, { action: 'update_card', cardId: card.id, coordinationOnly: true, title: 'Cannot exempt' }] }));
  assert.ok(chat && 'actions' in chat); assert.ok(chat.actions.actions.every(action => !('coordinationOnly' in action)));
});
