import assert from 'node:assert/strict';
import test from 'node:test';
import { randomUUID } from 'node:crypto';
import { eq } from 'drizzle-orm';
import { isolatedPostgres } from './test-support/postgres-db.ts';
test('PostgreSQL combined goal assessment survives normal child fence and atomically seals parent', {skip:!process.env.TEST_DATABASE_URL&&!process.env.CI?'TEST_DATABASE_URL absent; isolated PostgreSQL checks run in CI':false,timeout:60000}, async t=>{
 const {db}=await isolatedPostgres(t);
 const {companies,positions,agents,kanbanCards,workProducts,activityLog}=await import('./db/schema.ts');
 const {captureParentAssessment,tryReuseParentAssessment}=await import('./parent-assessment.ts');
 const {receiptFromParentAssessment}=await import('./assessment-reuse.ts');
 const {sealDeliveryAcceptance,acceptedCardProducts}=await import('./delivery-acceptance.ts');
 const [company]=await db.insert(companies).values({name:'Assessment',slug:`assessment-${randomUUID()}`}).returning();
 const [position]=await db.insert(positions).values({companyId:company!.id,name:'Boss',slug:'boss',isCompanyBoss:true}).returning();
 const [boss]=await db.insert(agents).values({companyId:company!.id,positionId:position!.id,name:'Boss',slug:'boss',role:'manager',adapterType:'webhook'}).returning();
 const [head]=await db.insert(agents).values({companyId:company!.id,name:'Head',slug:'head',role:'worker',adapterType:'webhook'}).returning();
 const [parent]=await db.insert(kanbanCards).values({companyId:company!.id,title:'Goal',body:'Parent acceptance',assigneeId:boss!.id,columnStatus:'in_progress',rollupStatus:'waiting_on_children'}).returning();
 const [child]=await db.insert(kanbanCards).values({companyId:company!.id,parentCardId:parent!.id,title:'Department report',body:'Child acceptance',assigneeId:head!.id,reviewerId:boss!.id,columnStatus:'in_review'}).returning();
 await db.insert(workProducts).values({companyId:company!.id,cardId:child!.id,agentId:head!.id,type:'report',title:'Original report',summary:'Checked evidence'});
 const capture=await captureParentAssessment(child!,boss!.id);assert.ok(capture);
 const report:any={kind:'megacorps-report',status:'completed',summary:'Accepted',verdict:'approved',parentAssessment:{token:capture.token,verdict:'approved',summary:'Goal covered by original report'}};
 const output=JSON.stringify(report);const receipt=receiptFromParentAssessment(capture,report,output);assert.ok(receipt);
 await db.update(kanbanCards).set({columnStatus:'done',reviewFeedback:output}).where(eq(kanbanCards.id,child!.id));
 await sealDeliveryAcceptance(child!.id);
 await db.insert(activityLog).values({companyId:company!.id,actorType:'agent',actorId:boss!.id,agentId:boss!.id,action:'review.approved',entityType:'card',entityId:child!.id,details:{parentAssessment:receipt}});
 const done=await tryReuseParentAssessment(parent!.id);assert.equal(done?.columnStatus,'done');assert.ok(done?.deliveryAcceptance);
 const [freshChild]=await db.select().from(kanbanCards).where(eq(kanbanCards.id,child!.id));
 const inherited=await acceptedCardProducts(freshChild!);assert.ok(inherited);
 assert.ok(await acceptedCardProducts(done!,undefined,inherited));
 assert.equal(await tryReuseParentAssessment(parent!.id),null);
});
