import { CEO_POSITION_PROMPT } from '../role-playbooks.ts';
import { companyDeletionInventory, lockCompanyInventory, type InventorySql } from '../company-inventory.ts';

/** Only the untouched legacy bootstrap seed is eligible; any use preserves it. */
export async function cleanupUnusedDefault(tx: InventorySql): Promise<boolean> {
  const catalog = await lockCompanyInventory(tx);
  const [company] = await tx.unsafe("SELECT * FROM companies WHERE slug='default'");
  if (!company) return false;
  const expected: Record<string, unknown> = { group_id: null, name: 'Default Company', slug: 'default', mission: null, boss_role_prompt: null, nfs_share_url: null, max_children_per_card: 3, panel_review_default: 'critical_only', dispatch_interval_seconds: 10, auto_dispatch_enabled: true };
  if (Object.entries(company).some(([key, value]) => !['id','created_at'].includes(key) && (!(key in expected) || value !== expected[key]))) return false;
  const inventory = await companyDeletionInventory(tx, company.id, catalog);
  if (Object.entries(inventory).some(([table, rows]) => table !== 'positions' && rows.count > 0)) return false;
  const roles = await tx.unsafe('SELECT * FROM positions WHERE company_id=$1', [company.id]);
  const expectedPosition: Record<string, unknown> = { company_id: company.id, name: 'CEO', slug: 'ceo', prompt: CEO_POSITION_PROMPT, description: 'Default company boss position generated by migration.', rank: 0, is_company_boss: true, can_delegate_across_departments: true, default_department_id: null, manager_position_id: null, review_domain: null, is_active: true };
  if (roles.length !== 1 || inventory.positions?.count !== 1 || Object.entries(roles[0]).some(([key, value]) => !['id','created_at','updated_at'].includes(key) && (!(key in expectedPosition) || value !== expectedPosition[key]))) return false;
  await tx.unsafe('DELETE FROM positions WHERE company_id=$1', [company.id]);
  await tx.unsafe('DELETE FROM companies WHERE id=$1', [company.id]);
  return true;
}
