import type { Locale } from './i18n';

const en = {
  title: 'Budget', subtitle: 'Track recorded usage and set limits for new work.',
  knownTotal: 'Known total', monthlyKnown: 'Known cost this month', actual: 'Runtime reported', estimated: 'Estimated', unknown: 'Unknown cost attempts', reserved: 'Currently reserved', summary: 'Usage summary',
  period: 'Period', allTime: 'All time', month: 'Month (UTC)', reportCompany: 'Reporting company', reportAgent: 'Reporting agent', allCompanies: 'All visible companies', allAgents: 'All agents',
  knownHint: 'Known total includes runtime-reported and estimated costs. Missing costs are excluded; these are not reconciled provider invoices.',
  reservationHint: 'Reservations cover work still in progress now, including work started in an earlier month. They are not settled costs.',
  scopeHint: 'Card limits cover that card’s executions, retries and reviews. Child cards are counted independently; company and project totals include all related work once.',
  enforcementHint: 'Limits check recorded costs and active reservations before new work. Missing provider costs and late reports can exceed a limit; it is not a guaranteed provider billing cap.',
  loading: 'Loading…', retryUsage: 'Retry usage', retryData: 'Retry data', refresh: 'Refresh', unavailable: 'Unavailable',
  limits: 'Policies', agentLimits: 'Agent limits', company: 'Company', agentScope: 'Agent scope', companyScope: 'All agents in company', name: 'Name', monthlyLimit: 'Monthly limit USD', perTaskLimit: 'Direct card limit USD', warn: 'Warn at percent', hard: 'Stop new work at the limit', active: 'Policy active',
  save: 'Save policy', saving: 'Saving…', saved: 'Budget policy saved', deleted: 'Budget policy deleted', create: 'New', edit: 'Edit', delete: 'Delete', deleteConfirm: 'Delete budget policy', editPolicy: 'Edit budget policy', newPolicy: 'New budget policy',
  none: 'None', noLimit: 'No limit', warningOnly: 'Warning only', hardStop: 'Stop new work', inactive: 'Inactive policy', manualPaused: 'Agent paused', enabled: 'Agent enabled',
  attempts: 'Recent attempts (all time)', unknownCost: 'Unknown cost', legacyEstimate: 'Legacy estimate', noProvider: 'Provider unavailable', tokens: 'Tokens', tokenActual: 'Reported tokens', tokenEstimated: 'Estimated tokens', tokenUnknown: 'Unknown tokens',
  next: 'Next attempts', previous: 'Previous attempts', page: 'Page', approvals: 'Pending approvals (up to 100)', approve: 'Approve', reject: 'Reject', approvalSaved: 'Approval updated', noCard: 'No card',
  noCompany: 'Create a company to start tracking usage and setting limits.', start: 'Set up a company', policyUnavailable: 'Select a company and enter a policy name.',
};
type Copy = Record<keyof typeof en, string>;
export const budgetCopy: Record<Locale, Copy> = {
  en,
  'zh-TW': {
    title: '預算', subtitle: '查看已記錄用量，設定新工作的執行限額。',
    knownTotal: '已知總成本', monthlyKnown: '本月已知成本', actual: 'Runtime 實報', estimated: '估算', unknown: '成本未知的執行次數', reserved: '目前預留額', summary: '用量摘要',
    period: '統計期間', allTime: '全部期間', month: '月份（UTC）', reportCompany: '統計公司', reportAgent: '統計 Agent', allCompanies: '所有可見公司', allAgents: '所有 Agent',
    knownHint: '已知總成本包含 runtime 實報與估算；缺少的成本不計入。這些數字尚未與供應商帳單核對。',
    reservationHint: '預留額涵蓋目前尚在執行的工作，包含上個月開始的工作，並非已結算費用。',
    scopeHint: '卡片限額涵蓋該卡的執行、重試與審查。子卡獨立計算；公司與專案總額會將所有相關工作各計一次。',
    enforcementHint: '開始新工作前會檢查已記錄成本與有效預留額。供應商缺少用量或回報延遲時仍可能超額，無法保證外部帳單不超過限額。',
    loading: '載入中…', retryUsage: '重試用量', retryData: '重新載入資料', refresh: '重新整理', unavailable: '無法取得',
    limits: '預算政策', agentLimits: 'Agent 限額', company: '公司', agentScope: 'Agent 範圍', companyScope: '公司所有 Agent', name: '名稱', monthlyLimit: '每月限額（美元）', perTaskLimit: '單卡限額（美元）', warn: '警告百分比', hard: '達到限額時停止新工作', active: '啟用政策',
    save: '儲存政策', saving: '儲存中…', saved: '已儲存預算政策', deleted: '已刪除預算政策', create: '新增', edit: '編輯', delete: '刪除', deleteConfirm: '刪除預算政策', editPolicy: '編輯預算政策', newPolicy: '新增預算政策',
    none: '無', noLimit: '未設定限額', warningOnly: '僅警告', hardStop: '停止新工作', inactive: '政策未啟用', manualPaused: 'Agent 已暫停', enabled: 'Agent 已啟用',
    attempts: '最近執行紀錄（全部期間）', unknownCost: '成本未知', legacyEstimate: '歷史估算', noProvider: '供應商資料未知', tokens: 'Token', tokenActual: '實報 Token', tokenEstimated: '估算 Token', tokenUnknown: 'Token 未知',
    next: '下一頁執行紀錄', previous: '上一頁執行紀錄', page: '頁', approvals: '待審批（最多 100 筆）', approve: '核准', reject: '拒絕', approvalSaved: '已更新審批', noCard: '未關聯卡片',
    noCompany: '先建立公司，即可追蹤用量與設定限額。', start: '建立公司', policyUnavailable: '請選擇公司並輸入政策名稱。',
  },
  ja: {
    title: '予算', subtitle: '記録された使用量を確認し、新しい作業の上限を設定します。',
    knownTotal: '既知の合計費用', monthlyKnown: '今月の既知の費用', actual: 'Runtime の報告値', estimated: '推定', unknown: '費用不明の実行回数', reserved: '現在の予約額', summary: '使用量の概要',
    period: '集計期間', allTime: '全期間', month: '月（UTC）', reportCompany: '集計する会社', reportAgent: '集計する Agent', allCompanies: '閲覧可能なすべての会社', allAgents: 'すべての Agent',
    knownHint: '既知の合計は runtime の報告値と推定値です。不明な費用は含まず、プロバイダーの請求書とは未照合です。',
    reservationHint: '予約額は前月開始分を含む現在実行中の作業に対応し、確定費用ではありません。',
    scopeHint: 'カード上限はそのカードの実行、再試行、レビューに適用します。子カードは別計算し、会社とプロジェクトには関連作業を一度ずつ集計します。',
    enforcementHint: '新しい作業の前に記録済み費用と予約額を確認します。使用量の欠落や遅延報告では上限を超える可能性があり、外部請求の上限は保証しません。',
    loading: '読み込み中…', retryUsage: '使用量を再取得', retryData: 'データを再取得', refresh: '更新', unavailable: '取得できません',
    limits: '予算ポリシー', agentLimits: 'Agent の上限', company: '会社', agentScope: 'Agent の範囲', companyScope: '会社の全 Agent', name: '名前', monthlyLimit: '月額上限 USD', perTaskLimit: 'カード上限 USD', warn: '警告の割合', hard: '上限に達したら新しい作業を停止', active: 'ポリシーを有効化',
    save: 'ポリシーを保存', saving: '保存中…', saved: '予算ポリシーを保存しました', deleted: '予算ポリシーを削除しました', create: '新規', edit: '編集', delete: '削除', deleteConfirm: '予算ポリシーを削除', editPolicy: '予算ポリシーの編集', newPolicy: '予算ポリシーの作成',
    none: 'なし', noLimit: '上限なし', warningOnly: '警告のみ', hardStop: '新しい作業を停止', inactive: '無効なポリシー', manualPaused: 'Agent 一時停止中', enabled: 'Agent 有効',
    attempts: '最近の実行（全期間）', unknownCost: '費用不明', legacyEstimate: '過去の推定値', noProvider: 'プロバイダー不明', tokens: 'Token', tokenActual: '報告済み Token', tokenEstimated: '推定 Token', tokenUnknown: 'Token 不明',
    next: '次の実行ページ', previous: '前の実行ページ', page: 'ページ', approvals: '承認待ち（最大100件）', approve: '承認', reject: '却下', approvalSaved: '承認を更新しました', noCard: 'カードなし',
    noCompany: '会社を作成すると使用量の追跡と上限設定を始められます。', start: '会社を設定', policyUnavailable: '会社を選択し、ポリシー名を入力してください。',
  },
};
